# Generated by Django 2.1.7 on 2019-09-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Role',
            field=models.SmallIntegerField(verbose_name='角色'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
