# Generated by Django 2.1.7 on 2019-09-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrelation',
            options={'verbose_name': '用户关系表'},
        ),
        migrations.AlterModelTable(
            name='userrelation',
            table='userrelations',
        ),
    ]
