# Generated by Django 2.1.7 on 2019-09-04 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190904_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrelation',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.Category', verbose_name='所在类别'),
        ),
    ]
