# Generated by Django 2.1.7 on 2019-09-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190907_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='Role_id',
        ),
    ]
